In [1]:
# importing numpy library
import numpy as np

In [3]:
# Creating a NumPy array and Matrix

narray = np.array([1,2,3,4])
matrix = np.array([[1,2],[3,4]])
print(narray)
print(matrix)

[1 2 3 4]
[[1 2]
 [3 4]]


In [5]:
# Zero and One Array - np.zeros(shape, dtype) OR np.zeros(shape)
zarray = np.zeros(5)
oarray = np.ones(5)
print(zarray)
print(oarray)

# Zero and One Matrix 
zmatrix = np.zeros((3,3,3))
omatrix = np.ones((3,2))
print(zmatrix)
print(omatrix)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
# Creating an array of 5 random integers between 1 and 10

arr = np.random.randint(1, 11, 5)
print(arr)

# Creating a N x N array of random floats between 0 and 1 (1 exclusive)
arr2 = np.random.rand(2, 2, 2)
print(arr2)

[9 2 9 5 9]
[[[0.97387177 0.45467031]
  [0.45957366 0.35392966]]

 [[0.65334773 0.75374078]
  [0.41656714 0.81587069]]]


In [93]:
# ARANGE = np.arange(start, end, step_size)

a_array = np.arange(0,200,5)
print(a_array)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195]


In [95]:
# LINSPACE = np.linspace(start, end, no_of_elements)
# spacing bw elements = (end - start) / (no_of_elements - 1)

l_array = np.linspace(0,3,5)
print(l_array)

[0.   0.75 1.5  2.25 3.  ]


In [99]:
# np.RANDOM.RAND(N) - Array of N random floats between 0 and 1
r1_array = np.random.rand(20)
print(r1_array)

# np.RANDOM.RANDINT(a,b,N) - N random integers between a and b
r2_array = np.random.randint(1,50,15)   
print(r2_array)

[0.9408445  0.63310452 0.54151064 0.60303489 0.30466033 0.68857295
 0.99940099 0.36116024 0.68151086 0.44908478 0.77541341 0.63088356
 0.17017147 0.59891659 0.79199354 0.5605505  0.37453766 0.5581082
 0.50008057 0.65381531]
[36  2 37 40 22 28 34 13 18  6 26 40 30 19 24]


In [103]:
# Basic statistical operations
print("Minimum:", np.min(r2_array))
print("Maximum:", np.max(r2_array))
print("Sum:",     np.sum(r2_array))
print("Mean:",    np.mean(r2_array))
print("Median:",  np.median(r2_array))


Minimum: 2
Maximum: 40
Sum: 375
Mean: 25.0
Median: 26.0


In [135]:
# Custom 9x9 Matrix:
# 1 1 1 1 1 1 1 1 1
# 1 0 0 0 0 0 0 0 1
# 1 0 3 0 0 0 0 0 1
# 1 0 0 3 0 0 0 0 1
# 1 0 0 0 3 0 0 0 1
# 1 0 0 0 0 3 0 0 1
# 1 0 0 0 0 0 3 0 1
# 1 0 0 0 0 0 0 0 1
# 1 1 1 1 1 1 1 1 1

a = np.ones((9,9))
b = np.zeros((7,7))
c = np.identity(5) * 3
print(a)
print(b)
print(c)
a[1:8, 1:8] = b
print(a)
a[2:7,2:7] = c
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[3. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 3.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 3. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 3. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 3. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 3. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0